---
- include: router_config.yml
  when: router_reset is defined and router_reset == "true"
- include: router_config_reset.yml
  when: router_reset is defined and router_reset == "false"
- include: harden_ios.yml
  when: harden_ios is defined and harden_ios == "true"
